spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: fred
    password: MrB@dGu1
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
jwt:
 secret: f7JBW4ukc4HTqa9L
oauth:
 google:
  token-url: https://oauth2.googleapis.com/token
  user-info-url: https://www.googleapis.com/oauth2/v1/userinfo
  id: 522113449269-9tbdnt6fr4ic7p4f60fgm19p905tvanp.apps.googleusercontent.com
  secret: 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
  redirect: http://localhost/api/oauth/google